//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Turtlebot3
{
    [Serializable]
    public class SoundMsg : Message
    {
        public const string k_RosMessageName = "turtlebot3_msgs/Sound";
        public override string RosMessageName => k_RosMessageName;

        // #######################################
        //  CONSTANTS
        // #######################################
        public const byte OFF = 0;
        public const byte ON = 1;
        public const byte LOW_BATTERY = 2;
        public const byte ERROR = 3;
        public const byte BUTTON1 = 4;
        public const byte BUTTON2 = 5;
        // #######################################
        //  Messages
        // #######################################
        public byte value;

        public SoundMsg()
        {
            this.value = 0;
        }

        public SoundMsg(byte value)
        {
            this.value = value;
        }

        public static SoundMsg Deserialize(MessageDeserializer deserializer) => new SoundMsg(deserializer);

        private SoundMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "SoundMsg: " +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
